name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Log in to Docker Hub
      run: echo "dckr_pat_SZPU1pLCeG47tGiUFzppG93Zi0c" | docker login -u hemangsah --password-stdin
    
    - name: Build Docker image
      run: docker build -t hemangsah/ci-cd-app:latest .
    
    - name: Push Docker image
      run: docker push hemangsah/ci-cd-app:latest
